# =============================================================================
# dockyard — shared Makefile: setup
# Included by each template's Makefile.
# Provides: make setup (interactive .env generator)
# =============================================================================

# .env is written to VOLUMES_BASE (outside the repo, in the deployment path).
# Variables:  CONTAINER_NAME, AGENT_UID, AGENT_GID, SSH_PORT

.PHONY: setup

setup:
	@echo "=== Dockyard Deployment Setup ==="
	@echo ""
	@hostcfg="$(HOME)/.dockyard"; \
	 if [ -f "$$hostcfg" ]; then . "$$hostcfg"; fi; \
	 if [ -z "$${VOLUMES_ROOT:-}" ]; then \
	   read -p "Volumes root path (e.g. /tank/docker/volumes/dockyard): " VOLUMES_ROOT; \
	   printf "VOLUMES_ROOT=$$VOLUMES_ROOT\n" > "$$hostcfg"; \
	   echo "  Written VOLUMES_ROOT to $$hostcfg"; \
	 else \
	   echo "  Volumes root: $$VOLUMES_ROOT  (from $$hostcfg)"; \
	 fi; \
	 echo ""; \
	 read -p "Deployment name              : " name; \
	 read -p "Agent UID         (e.g. 1101):          " uid; \
	 read -p "SSH port on host  (e.g. 2201):          " port; \
	 envdir="$$VOLUMES_ROOT/$$name"; \
	 sudo mkdir -p "$$envdir"; \
	 envfile="$$envdir/.env"; \
	 if [ -f "$$envfile" ]; then \
	   sudo sed -i '/^CONTAINER_NAME=/d;/^AGENT_UID=/d;/^AGENT_GID=/d;/^SSH_PORT=/d;/^# Deployment parameters/d' "$$envfile"; \
	 fi; \
	 printf "# Deployment parameters (generated by 'make setup')\nCONTAINER_NAME=$$name\nAGENT_UID=$$uid\nAGENT_GID=$$uid\nSSH_PORT=$$port\n" | sudo tee -a "$$envfile" > /dev/null; \
	 echo ""; \
	 echo "Written to $$envfile:"; \
	 cat "$$envfile"; \
	 echo ""; \
	 echo "Next: run 'make deploy CONTAINER_NAME=$$name'"
