# =============================================================================
# dockyard — shared Makefile: setup
# Included by each template's Makefile.
# Provides: make setup (interactive .env generator)
# =============================================================================

# .env is written to VOLUMES_BASE (outside the repo, in the deployment path).
# Variables:  CONTAINER_NAME, AGENT_UID, AGENT_GID, SSH_PORT

.PHONY: setup

setup:
	@echo "=== Dockyard Deployment Setup ==="
	@echo ""
	@hostcfg="$(HOME)/.config/dockyard/.env"; \
	 mkdir -p "$(HOME)/.config/dockyard"; \
	 if [ -f "$$hostcfg" ]; then . "$$hostcfg"; fi; \
	 if [ -z "$${VOLUMES_ROOT:-}" ]; then \
	   defvol="$(HOME)/.config/dockyard/volumes"; \
	   read -p "Volumes root path [$$defvol]: " VOLUMES_ROOT; \
	   VOLUMES_ROOT="$${VOLUMES_ROOT:-$$defvol}"; \
	   printf "VOLUMES_ROOT=$$VOLUMES_ROOT\n" > "$$hostcfg"; \
	   echo "  Written VOLUMES_ROOT to $$hostcfg"; \
	 else \
	   echo "  Volumes root: $$VOLUMES_ROOT  (from $$hostcfg)"; \
	 fi; \
	 echo ""; \
	 read -p "Deployment name              : " name; \
	 defuid=1100; \
	 while getent passwd "$$defuid" >/dev/null 2>&1; do defuid=$$((defuid + 1)); done; \
	 read -p "Agent UID                [$$defuid]: " uid; \
	 uid="$${uid:-$$defuid}"; \
	 defport=2200; \
	 while ss -tlnH 2>/dev/null | awk '{print $$4}' | grep -q ":$$defport$$"; do defport=$$((defport + 1)); done; \
	 read -p "SSH port on host         [$$defport]: " port; \
	 port="$${port:-$$defport}"; \
	 envdir="$$VOLUMES_ROOT/$$name"; \
	 sudo mkdir -p "$$envdir"; \
	 envfile="$$envdir/.env"; \
	 if [ -f "$$envfile" ]; then \
	   sudo sed -i '/^CONTAINER_NAME=/d;/^AGENT_UID=/d;/^AGENT_GID=/d;/^SSH_PORT=/d;/^# Deployment parameters/d' "$$envfile"; \
	 fi; \
	 printf "# Deployment parameters (generated by 'make setup')\nCONTAINER_NAME=$$name\nAGENT_UID=$$uid\nAGENT_GID=$$uid\nSSH_PORT=$$port\n" | sudo tee -a "$$envfile" > /dev/null; \
	 echo ""; \
	 echo "Written to $$envfile:"; \
	 cat "$$envfile"; \
	 echo ""; \
	 echo "Next: run 'make deploy CONTAINER_NAME=$$name'"
