package config

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"

	"gopkg.in/yaml.v3"
)

// Deployment represents a single dockyard instance persisted at
// $VolumesRoot/<name>/config.yaml.
type Deployment struct {
	Name          string            `yaml:"name"`
	Template      string            `yaml:"template"`
	ContainerName string            `yaml:"container_name"`
	AgentUID      int               `yaml:"agent_uid"`
	AgentGID      int               `yaml:"agent_gid"`
	SSHPort       int               `yaml:"ssh_port"`
	BuildArgs     map[string]string `yaml:"build_args,omitempty"`
}

// DeploymentDir returns $VolumesRoot/<name>.
func DeploymentDir(volumesRoot, name string) string {
	return filepath.Join(volumesRoot, name)
}

// DeploymentConfigPath returns $VolumesRoot/<name>/config.yaml.
func DeploymentConfigPath(volumesRoot, name string) string {
	return filepath.Join(DeploymentDir(volumesRoot, name), "config.yaml")
}

// DeploymentEnvPath returns $VolumesRoot/<name>/.env — still written for
// docker compose --env-file consumption.
func DeploymentEnvPath(volumesRoot, name string) string {
	return filepath.Join(DeploymentDir(volumesRoot, name), ".env")
}

// LoadDeployment loads a deployment's config, preferring config.yaml and
// falling back to parsing the legacy .env file.
func LoadDeployment(volumesRoot, name string) (*Deployment, error) {
	yamlPath := DeploymentConfigPath(volumesRoot, name)
	data, err := os.ReadFile(yamlPath)
	if err == nil {
		var d Deployment
		if err := yaml.Unmarshal(data, &d); err != nil {
			return nil, fmt.Errorf("parse %s: %w", yamlPath, err)
		}
		if d.Name == "" {
			d.Name = name
		}
		if d.ContainerName == "" {
			d.ContainerName = name
		}
		if d.AgentGID == 0 {
			d.AgentGID = d.AgentUID
		}
		return &d, nil
	}
	if !errors.Is(err, fs.ErrNotExist) {
		return nil, err
	}

	// Legacy .env fallback — used to migrate existing Make-based deployments.
	envPath := DeploymentEnvPath(volumesRoot, name)
	kv, err := readEnvFile(envPath)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, nil
		}
		return nil, err
	}
	d := &Deployment{
		Name:          name,
		ContainerName: firstNonEmpty(kv["CONTAINER_NAME"], name),
		BuildArgs:     map[string]string{},
	}
	if s := kv["AGENT_UID"]; s != "" {
		if n, err := strconv.Atoi(s); err == nil {
			d.AgentUID = n
		}
	}
	if s := kv["AGENT_GID"]; s != "" {
		if n, err := strconv.Atoi(s); err == nil {
			d.AgentGID = n
		}
	} else {
		d.AgentGID = d.AgentUID
	}
	if s := kv["SSH_PORT"]; s != "" {
		if n, err := strconv.Atoi(s); err == nil {
			d.SSHPort = n
		}
	}
	// Template is unknown in legacy .env — caller should set it.
	// Any other keys are treated as build args.
	known := map[string]struct{}{
		"CONTAINER_NAME": {}, "AGENT_UID": {}, "AGENT_GID": {}, "SSH_PORT": {},
	}
	for k, v := range kv {
		if _, skip := known[k]; skip {
			continue
		}
		d.BuildArgs[k] = v
	}
	return d, nil
}

// Save writes both config.yaml (canonical) and .env (for docker compose).
func (d *Deployment) Save(volumesRoot string) error {
	dir := DeploymentDir(volumesRoot, d.Name)
	if err := MkdirAllPrivileged(dir, 0o755); err != nil {
		return err
	}
	// Make the deployment dir writable by the calling user so that subsequent
	// operations (staging build context, writing .env) work without sudo.
	if err := ChownToSelf(dir); err != nil {
		return err
	}

	yamlPath := DeploymentConfigPath(volumesRoot, d.Name)
	data, err := yaml.Marshal(d)
	if err != nil {
		return err
	}
	if err := WriteFilePrivileged(yamlPath, data, 0o644); err != nil {
		return err
	}
	return d.WriteEnvFile(volumesRoot)
}

// WriteEnvFile regenerates the $VolumesRoot/<name>/.env file.
func (d *Deployment) WriteEnvFile(volumesRoot string) error {
	var b []byte
	b = append(b, "# Generated by dockyard — do not edit by hand\n"...)
	b = appendKV(b, "CONTAINER_NAME", d.ContainerName)
	b = appendKV(b, "AGENT_UID", strconv.Itoa(d.AgentUID))
	b = appendKV(b, "AGENT_GID", strconv.Itoa(d.AgentGID))
	b = appendKV(b, "SSH_PORT", strconv.Itoa(d.SSHPort))
	b = appendKV(b, "VOLUMES_BASE", d.Base(volumesRoot))
	// Deterministic key order.
	keys := make([]string, 0, len(d.BuildArgs))
	for k := range d.BuildArgs {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		b = appendKV(b, k, d.BuildArgs[k])
	}
	return WriteFilePrivileged(DeploymentEnvPath(volumesRoot, d.Name), b, 0o644)
}

// Base returns $VolumesRoot/<name>.
func (d *Deployment) Base(volumesRoot string) string {
	return DeploymentDir(volumesRoot, d.Name)
}

// ListDeployments scans $VolumesRoot for any directory containing either a
// config.yaml or a legacy .env file.
func ListDeployments(volumesRoot string) ([]string, error) {
	entries, err := os.ReadDir(volumesRoot)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, nil
		}
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		if _, err := os.Stat(DeploymentConfigPath(volumesRoot, name)); err == nil {
			out = append(out, name)
			continue
		}
		if _, err := os.Stat(DeploymentEnvPath(volumesRoot, name)); err == nil {
			out = append(out, name)
		}
	}
	sort.Strings(out)
	return out, nil
}

func appendKV(b []byte, k, v string) []byte {
	return append(b, fmt.Sprintf("%s=%s\n", k, v)...)
}

func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if v != "" {
			return v
		}
	}
	return ""
}
